const data = [{
    "id": 379686,
    "original_language": "en",
    "original_title": "Space Jam: A New Legacy",
    "overview": "When LeBron and his young son Dom are trapped in a digital space by a rogue A.I., LeBron must get them home safe by leading Bugs, Lola Bunny and the whole gang of notoriously undisciplined Looney Tunes to victory over the A.I.'s digitized champions on the court. It's Tunes versus Goons in the highest-stakes challenge of his life.",
    "popularity": 9054.455,
    "poster_path": "https://image.tmdb.org/t/p/original/5bFK5d3mVTAvBCXi5NPWH0tYjKl.jpg",
    "release_date": "2021-07-08",
    "title": "Space Jam: A New Legacy",
    "video": false,
    "vote_average": 7.8,
    "vote_count": 1185
},
{
    "id": 497698,
    "original_language": "en",
    "original_title": "Black Widow",
    "overview": "Natasha Romanoff, also known as Black Widow, confronts the darker parts of her ledger when a dangerous conspiracy with ties to her past arises. Pursued by a force that will stop at nothing to bring her down, Natasha must deal with her history as a spy and the broken relationships left in her wake long before she became an Avenger.",
    "popularity": 7107.473,
    "poster_path": "https://image.tmdb.org/t/p/original/qAZ0pzat24kLdO3o8ejmbLxyOac.jpg",
    "release_date": "2021-07-07",
    "title": "Black Widow",
    "video": false,
    "vote_average": 8,
    "vote_count": 3285
},
{
    "id": 602223,
    "original_language": "en",
    "original_title": "The Forever Purge",
    "overview": "All the rules are broken as a sect of lawless marauders decides that the annual Purge does not stop at daybreak and instead should never end as they chase a group of immigrants who they want to punish because of their harsh historical past.",
    "popularity": 7221.498,
    "poster_path": "https://image.tmdb.org/t/p/original/uHA5COgDzcxjpYSHHulrKVl6ByL.jpg",
    "release_date": "2021-06-30",
    "title": "The Forever Purge",
    "video": false,
    "vote_average": 7.9,
    "vote_count": 535
},
{
    "id": 459151,
    "original_language": "en",
    "original_title": "The Boss Baby: Family Business",
    "overview": "The Templeton brothers — Tim and his Boss Baby little bro Ted — have become adults and drifted away from each other. But a new boss baby with a cutting-edge approach and a can-do attitude is about to bring them together again … and inspire a new family business.",
    "popularity": 5100.392,
    "poster_path": "https://image.tmdb.org/t/p/original/5dExO5G2iaaTxYnLIFKLWofDzyI.jpg",
    "release_date": "2021-07-01",
    "title": "The Boss Baby: Family Business",
    "video": false,
    "vote_average": 7.9,
    "vote_count": 874
},
{
    "id": 508943,
    "original_language": "en",
    "original_title": "Luca",
    "overview": "Luca and his best friend Alberto experience an unforgettable summer on the Italian Riviera. But all the fun is threatened by a deeply-held secret: they are sea monsters from another world just below the water’s surface.",
    "popularity": 3383.138,
    "poster_path": "https://image.tmdb.org/t/p/original/jTswp6KyDYKtvC52GbHagrZbGvD.jpg",
    "release_date": "2021-06-17",
    "title": "Luca",
    "video": false,
    "vote_average": 8.1,
    "vote_count": 3202
},
{
    "id": 581726,
    "original_language": "en",
    "original_title": "Infinite",
    "overview": "Evan McCauley has skills he never learned and memories of places he has never visited. Self-medicated and on the brink of a mental breakdown, a secret group that call themselves “Infinites” come to his rescue, revealing that his memories are real.",
    "popularity": 2914.38,
    "poster_path": "https://image.tmdb.org/t/p/original/niw2AKHz6XmwiRMLWaoyAOAti0G.jpg",
    "release_date": "2021-06-10",
    "title": "Infinite",
    "video": false,
    "vote_average": 7.3,
    "vote_count": 538
},
{
    "id": 385128,
    "original_language": "en",
    "original_title": "F9",
    "overview": "Dominic Toretto and his crew battle the most skilled assassin and high-performance driver they've ever encountered: his forsaken brother.",
    "popularity": 2381.183,
    "poster_path": "https://image.tmdb.org/t/p/original/bOFaAXmWWXC3Rbv4u4uM9ZSzRXP.jpg",
    "release_date": "2021-05-19",
    "title": "F9",
    "video": false,
    "vote_average": 7.5,
    "vote_count": 721
},
{
    "id": 637649,
    "original_language": "en",
    "original_title": "Wrath of Man",
    "overview": "A cold and mysterious new security guard for a Los Angeles cash truck company surprises his co-workers when he unleashes precision skills during a heist. The crew is left wondering who he is and where he came from. Soon, the marksman's ultimate motive becomes clear as he takes dramatic and irrevocable steps to settle a score.",
    "popularity": 2369.428,
    "poster_path": "https://image.tmdb.org/t/p/original/M7SUK85sKjaStg4TKhlAVyGlz3.jpg",
    "release_date": "2021-04-22",
    "title": "Wrath of Man",
    "video": false,
    "vote_average": 7.8,
    "vote_count": 1537
},
{
    "id": 522478,
    "original_language": "en",
    "original_title": "Peter Rabbit 2: The Runaway",
    "overview": "Bea, Thomas, and the rabbits have created a makeshift family, but despite his best efforts, Peter can’t seem to shake his mischievous reputation. Adventuring out of the garden, Peter finds himself in a world where his mischief is appreciated, but when his family risks everything to come looking for him, Peter must figure out what kind of bunny he wants to be.",
    "popularity": 1987.614,
    "poster_path": "https://image.tmdb.org/t/p/original/cycDz68DtTjJrDJ1fV8EBq2Xdpb.jpg",
    "release_date": "2021-03-25",
    "title": "Peter Rabbit 2: The Runaway",
    "video": false,
    "vote_average": 7.4,
    "vote_count": 197
},
{
    "id": 337404,
    "original_language": "en",
    "original_title": "Cruella",
    "overview": "In 1970s London amidst the punk rock revolution, a young grifter named Estella is determined to make a name for herself with her designs. She befriends a pair of young thieves who appreciate her appetite for mischief, and together they are able to build a life for themselves on the London streets. One day, Estella’s flair for fashion catches the eye of the Baroness von Hellman, a fashion legend who is devastatingly chic and terrifyingly haute. But their relationship sets in motion a course of events and revelations that will cause Estella to embrace her wicked side and become the raucous, fashionable and revenge-bent Cruella.",
    "popularity": 2111.396,
    "poster_path": "https://image.tmdb.org/t/p/original/rTh4K5uw9HypmpGslcKd4QfHl93.jpg",
    "release_date": "2021-05-26",
    "title": "Cruella",
    "video": false,
    "vote_average": 8.4,
    "vote_count": 4322
}

]

export default data